#!/usr/bin/env ruby

require "tw_schedule_it"
require "tw_schedule_it/cli"

talks_file_path = ARGV[0]

if talks_file_path == nil || !File.file?(File.expand_path(talks_file_path))
  puts "Error: You must pass a plain text file with the talk information as an argument to tw_schedule_it."
  exit(1)
end

app = TwScheduleIt::App.new(talks_file_path)
TwScheduleIt::CLI.new(app).start
