#!/usr/bin/env ruby

require "tw_schedule_it"
require "tw_schedule_it/cli"
require "tw_schedule_it/import_from_file"

talks_file_path = ARGV[0]

if talks_file_path == nil || !File.file?(File.expand_path(talks_file_path))
  puts "Error: You must pass a plain text file with the talk information as an argument to tw_schedule_it."
  exit(1)
end

talks_data = TwScheduleIt::ImportFromFile.build(talks_file_path)
schedule = TwScheduleIt::Schedule.new(
  TwScheduleIt::TalksFactory.build(talks_data))

TwScheduleIt::CLI.new(schedule.build).start
